version: 2
jobs:
  build:
    working_directory: ~/testrepo/testJS/testJS
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: false
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run "python manage.py test"